# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x0b\x63\x61mpus.auth\"%\n\x14ValidateTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\"W\n\x15ValidateTokenResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05roles\x18\x03 \x03(\t\x12\x0f\n\x07room_id\x18\x04 \x01(\t\"%\n\x12GetUserInfoRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"\xae\x01\n\x10UserInfoResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\x12\x12\n\nfirst_name\x18\x03 \x01(\t\x12\x12\n\npatronymic\x18\x04 \x01(\t\x12\x0f\n\x07room_id\x18\x05 \x01(\t\x12\r\n\x05roles\x18\x06 \x03(\t\x12\r\n\x05phone\x18\x07 \x01(\t\x12\r\n\x05\x65mail\x18\x08 \x01(\t\x12\x10\n\x08is_minor\x18\t \x01(\x08\">\n\x14\x43heckUserRoleRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rrequired_role\x18\x02 \x01(\t\")\n\x15\x43heckUserRoleResponse\x12\x10\n\x08has_role\x18\x01 \x01(\x08\"L\n\x0fGetUsersRequest\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0c\n\x04page\x18\x02 \x01(\x05\x12\x0c\n\x04size\x18\x03 \x01(\x05\x12\x0f\n\x07room_id\x18\x04 \x01(\t\"z\n\x10GetUsersResponse\x12,\n\x05users\x18\x01 \x03(\x0b\x32\x1d.campus.auth.UserInfoResponse\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x0c\n\x04page\x18\x03 \x01(\x05\x12\x0c\n\x04size\x18\x04 \x01(\x05\x12\r\n\x05pages\x18\x05 \x01(\x05\x32\xd5\x02\n\x0b\x41uthService\x12V\n\rValidateToken\x12!.campus.auth.ValidateTokenRequest\x1a\".campus.auth.ValidateTokenResponse\x12M\n\x0bGetUserInfo\x12\x1f.campus.auth.GetUserInfoRequest\x1a\x1d.campus.auth.UserInfoResponse\x12G\n\x08GetUsers\x12\x1c.campus.auth.GetUsersRequest\x1a\x1d.campus.auth.GetUsersResponse\x12V\n\rCheckUserRole\x12!.campus.auth.CheckUserRoleRequest\x1a\".campus.auth.CheckUserRoleResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VALIDATETOKENREQUEST']._serialized_start=27
  _globals['_VALIDATETOKENREQUEST']._serialized_end=64
  _globals['_VALIDATETOKENRESPONSE']._serialized_start=66
  _globals['_VALIDATETOKENRESPONSE']._serialized_end=153
  _globals['_GETUSERINFOREQUEST']._serialized_start=155
  _globals['_GETUSERINFOREQUEST']._serialized_end=192
  _globals['_USERINFORESPONSE']._serialized_start=195
  _globals['_USERINFORESPONSE']._serialized_end=369
  _globals['_CHECKUSERROLEREQUEST']._serialized_start=371
  _globals['_CHECKUSERROLEREQUEST']._serialized_end=433
  _globals['_CHECKUSERROLERESPONSE']._serialized_start=435
  _globals['_CHECKUSERROLERESPONSE']._serialized_end=476
  _globals['_GETUSERSREQUEST']._serialized_start=478
  _globals['_GETUSERSREQUEST']._serialized_end=554
  _globals['_GETUSERSRESPONSE']._serialized_start=556
  _globals['_GETUSERSRESPONSE']._serialized_end=678
  _globals['_AUTHSERVICE']._serialized_start=681
  _globals['_AUTHSERVICE']._serialized_end=1022
# @@protoc_insertion_point(module_scope)
