# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import application_pb2 as application__pb2

GRPC_GENERATED_VERSION = '1.78.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in application_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ApplicationServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetApprovedLeaves = channel.unary_unary(
                '/campus.application.ApplicationService/GetApprovedLeaves',
                request_serializer=application__pb2.GetApprovedLeavesRequest.SerializeToString,
                response_deserializer=application__pb2.GetApprovedLeavesResponse.FromString,
                _registered_method=True)
        self.ListApplications = channel.unary_unary(
                '/campus.application.ApplicationService/ListApplications',
                request_serializer=application__pb2.ListApplicationsRequest.SerializeToString,
                response_deserializer=application__pb2.ListApplicationsResponse.FromString,
                _registered_method=True)
        self.CreateApplication = channel.unary_unary(
                '/campus.application.ApplicationService/CreateApplication',
                request_serializer=application__pb2.CreateApplicationRequest.SerializeToString,
                response_deserializer=application__pb2.CreateApplicationResponse.FromString,
                _registered_method=True)
        self.GetApplication = channel.unary_unary(
                '/campus.application.ApplicationService/GetApplication',
                request_serializer=application__pb2.GetApplicationRequest.SerializeToString,
                response_deserializer=application__pb2.GetApplicationResponse.FromString,
                _registered_method=True)
        self.DecideApplication = channel.unary_unary(
                '/campus.application.ApplicationService/DecideApplication',
                request_serializer=application__pb2.DecideApplicationRequest.SerializeToString,
                response_deserializer=application__pb2.DecideApplicationResponse.FromString,
                _registered_method=True)
        self.UploadDocument = channel.unary_unary(
                '/campus.application.ApplicationService/UploadDocument',
                request_serializer=application__pb2.UploadDocumentRequest.SerializeToString,
                response_deserializer=application__pb2.UploadDocumentResponse.FromString,
                _registered_method=True)
        self.GetDocumentDownloadUrl = channel.unary_unary(
                '/campus.application.ApplicationService/GetDocumentDownloadUrl',
                request_serializer=application__pb2.GetDocumentDownloadUrlRequest.SerializeToString,
                response_deserializer=application__pb2.GetDocumentDownloadUrlResponse.FromString,
                _registered_method=True)
        self.DeleteDocument = channel.unary_unary(
                '/campus.application.ApplicationService/DeleteDocument',
                request_serializer=application__pb2.DeleteDocumentRequest.SerializeToString,
                response_deserializer=application__pb2.DeleteDocumentResponse.FromString,
                _registered_method=True)


class ApplicationServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetApprovedLeaves(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListApplications(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DecideApplication(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDocumentDownloadUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ApplicationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetApprovedLeaves': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApprovedLeaves,
                    request_deserializer=application__pb2.GetApprovedLeavesRequest.FromString,
                    response_serializer=application__pb2.GetApprovedLeavesResponse.SerializeToString,
            ),
            'ListApplications': grpc.unary_unary_rpc_method_handler(
                    servicer.ListApplications,
                    request_deserializer=application__pb2.ListApplicationsRequest.FromString,
                    response_serializer=application__pb2.ListApplicationsResponse.SerializeToString,
            ),
            'CreateApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateApplication,
                    request_deserializer=application__pb2.CreateApplicationRequest.FromString,
                    response_serializer=application__pb2.CreateApplicationResponse.SerializeToString,
            ),
            'GetApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.GetApplication,
                    request_deserializer=application__pb2.GetApplicationRequest.FromString,
                    response_serializer=application__pb2.GetApplicationResponse.SerializeToString,
            ),
            'DecideApplication': grpc.unary_unary_rpc_method_handler(
                    servicer.DecideApplication,
                    request_deserializer=application__pb2.DecideApplicationRequest.FromString,
                    response_serializer=application__pb2.DecideApplicationResponse.SerializeToString,
            ),
            'UploadDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadDocument,
                    request_deserializer=application__pb2.UploadDocumentRequest.FromString,
                    response_serializer=application__pb2.UploadDocumentResponse.SerializeToString,
            ),
            'GetDocumentDownloadUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDocumentDownloadUrl,
                    request_deserializer=application__pb2.GetDocumentDownloadUrlRequest.FromString,
                    response_serializer=application__pb2.GetDocumentDownloadUrlResponse.SerializeToString,
            ),
            'DeleteDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteDocument,
                    request_deserializer=application__pb2.DeleteDocumentRequest.FromString,
                    response_serializer=application__pb2.DeleteDocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'campus.application.ApplicationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('campus.application.ApplicationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ApplicationService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetApprovedLeaves(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/GetApprovedLeaves',
            application__pb2.GetApprovedLeavesRequest.SerializeToString,
            application__pb2.GetApprovedLeavesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListApplications(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/ListApplications',
            application__pb2.ListApplicationsRequest.SerializeToString,
            application__pb2.ListApplicationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/CreateApplication',
            application__pb2.CreateApplicationRequest.SerializeToString,
            application__pb2.CreateApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/GetApplication',
            application__pb2.GetApplicationRequest.SerializeToString,
            application__pb2.GetApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DecideApplication(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/DecideApplication',
            application__pb2.DecideApplicationRequest.SerializeToString,
            application__pb2.DecideApplicationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/UploadDocument',
            application__pb2.UploadDocumentRequest.SerializeToString,
            application__pb2.UploadDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDocumentDownloadUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/GetDocumentDownloadUrl',
            application__pb2.GetDocumentDownloadUrlRequest.SerializeToString,
            application__pb2.GetDocumentDownloadUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/campus.application.ApplicationService/DeleteDocument',
            application__pb2.DeleteDocumentRequest.SerializeToString,
            application__pb2.DeleteDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
