from src.constants.error_codes import (
    DUTY_NOT_FOUND,
    DUTY_CONFLICT,
    REPORT_NOT_FOUND,
    IMAGE_NOT_FOUND,
    NOT_FOUND,
    CONFLICT,
    UNAUTHORIZED,
    FORBIDDEN,
    VALIDATION_ERROR,
    INTERNAL_ERROR,
    AUTH_SERVICE_UNAVAILABLE,
)

__all__ = [
    "DUTY_NOT_FOUND",
    "DUTY_CONFLICT",
    "REPORT_NOT_FOUND",
    "IMAGE_NOT_FOUND",
    "NOT_FOUND",
    "CONFLICT",
    "UNAUTHORIZED",
    "FORBIDDEN",
    "VALIDATION_ERROR",
    "INTERNAL_ERROR",
    "AUTH_SERVICE_UNAVAILABLE",
]
