from src.constants.document_type import (
    DOCUMENT_TYPE_SIGNED_APPLICATION,
    DOCUMENT_TYPE_PARENT_LETTER,
    DOCUMENT_TYPE_VOICE_MESSAGE,
    DOCUMENT_TYPES,
    SCAN_ALLOWED_EXTENSIONS,
    VOICE_ALLOWED_EXTENSIONS,
)
from src.constants.error_codes import (
    APP_APPLICATION_NOT_FOUND,
    APP_DOCUMENT_NOT_FOUND,
    APP_INVALID_DOCUMENT_TYPE,
    APP_MINOR_VOICE_REQUIRED,
    APP_FORBIDDEN,
    APP_ALREADY_DECIDED,
)

__all__ = [
    "DOCUMENT_TYPE_SIGNED_APPLICATION",
    "DOCUMENT_TYPE_PARENT_LETTER",
    "DOCUMENT_TYPE_VOICE_MESSAGE",
    "DOCUMENT_TYPES",
    "SCAN_ALLOWED_EXTENSIONS",
    "VOICE_ALLOWED_EXTENSIONS",
    "APP_APPLICATION_NOT_FOUND",
    "APP_DOCUMENT_NOT_FOUND",
    "APP_INVALID_DOCUMENT_TYPE",
    "APP_MINOR_VOICE_REQUIRED",
    "APP_FORBIDDEN",
    "APP_ALREADY_DECIDED",
]
