from typing import Literal

APP_APPLICATION_NOT_FOUND: Literal["APP_APPLICATION_NOT_FOUND"] = "APP_APPLICATION_NOT_FOUND"
APP_DOCUMENT_NOT_FOUND: Literal["APP_DOCUMENT_NOT_FOUND"] = "APP_DOCUMENT_NOT_FOUND"
APP_INVALID_DOCUMENT_TYPE: Literal["APP_INVALID_DOCUMENT_TYPE"] = "APP_INVALID_DOCUMENT_TYPE"
APP_MINOR_VOICE_REQUIRED: Literal["APP_MINOR_VOICE_REQUIRED"] = "APP_MINOR_VOICE_REQUIRED"
APP_FORBIDDEN: Literal["APP_FORBIDDEN"] = "APP_FORBIDDEN"
APP_ALREADY_DECIDED: Literal["APP_ALREADY_DECIDED"] = "APP_ALREADY_DECIDED"

ApplicationErrorCode = Literal[
    "APP_APPLICATION_NOT_FOUND",
    "APP_DOCUMENT_NOT_FOUND",
    "APP_INVALID_DOCUMENT_TYPE",
    "APP_MINOR_VOICE_REQUIRED",
    "APP_FORBIDDEN",
    "APP_ALREADY_DECIDED",
]
