from src.constants.error_codes import (
    PATROL_NOT_FOUND,
    PATROL_ENTRY_NOT_FOUND,
    PATROL_ALREADY_EXISTS,
    PATROL_ALREADY_COMPLETED,
    PATROL_NOT_IN_PROGRESS,
    VALIDATION_ERROR,
    UNAUTHORIZED,
    FORBIDDEN,
    INTERNAL_ERROR,
)

__all__ = [
    "PATROL_NOT_FOUND",
    "PATROL_ENTRY_NOT_FOUND",
    "PATROL_ALREADY_EXISTS",
    "PATROL_ALREADY_COMPLETED",
    "PATROL_NOT_IN_PROGRESS",
    "VALIDATION_ERROR",
    "UNAUTHORIZED",
    "FORBIDDEN",
    "INTERNAL_ERROR",
]
