from typing import Literal

COWORKING_NOT_FOUND: Literal["COWORKING_NOT_FOUND"] = "COWORKING_NOT_FOUND"
BOOKING_NOT_FOUND: Literal["BOOKING_NOT_FOUND"] = "BOOKING_NOT_FOUND"
COWORKING_NOT_AVAILABLE: Literal["COWORKING_NOT_AVAILABLE"] = "COWORKING_NOT_AVAILABLE"
BOOKING_INVALID_STATUS_TRANSITION: Literal["BOOKING_INVALID_STATUS_TRANSITION"] = (
    "BOOKING_INVALID_STATUS_TRANSITION"
)
BOOKING_ACCESS_DENIED: Literal["BOOKING_ACCESS_DENIED"] = "BOOKING_ACCESS_DENIED"
STUDENT_ALREADY_HAS_ACTIVE_BOOKING: Literal["STUDENT_ALREADY_HAS_ACTIVE_BOOKING"] = (
    "STUDENT_ALREADY_HAS_ACTIVE_BOOKING"
)

CoworkingErrorCode = Literal[
    "COWORKING_NOT_FOUND",
    "BOOKING_NOT_FOUND",
    "COWORKING_NOT_AVAILABLE",
    "BOOKING_INVALID_STATUS_TRANSITION",
    "BOOKING_ACCESS_DENIED",
    "STUDENT_ALREADY_HAS_ACTIVE_BOOKING",
]
